##### Prefix #####
# Use Ctrl + Space as prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g base-index 1
setw -g pane-base-index 1
set -g detach-on-destroy off

# Reload configuration quickly
unbind r
bind r source-file ~/dotfiles/tmux/tmux.conf \; display-message "Reloaded tmux.conf"
bind R refresh-client

##### Mouse & Clipboard #####
# Enable mouse support
set -g mouse on

# Sync tmux clipboard with OS clipboard (WSL / Windows)
set -g set-clipboard on

set-option -g renumber-windows on

##### Copy mode (Vim-style) #####
# Use Vim keys in copy-mode
setw -g mode-keys vi
set -sg escape-time 0
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi r send-keys -X rectangle-toggle
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi y send-keys -X copy-selection

#### selecting windows like tiling manager ####
bind u select-window -t 1
bind i select-window -t 2
bind o select-window -t 3
bind p select-window -t 4

##### Pane splitting #####
bind v split-window -h   # split right
bind s split-window -v   # split bottom

bind x kill-pane

#### resizing ####
bind -r H resize-pane -L 1
bind -r J resize-pane -D 1
bind -r K resize-pane -U 1
bind -r L resize-pane -R 1

set -g status-position top
set -g status-justify absolute-centre

# Allow vim keybinds to work correctly
set -g focus-events on

##### Terminal / Colors #####
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

# Window names
set -g automatic-rename off
set -g allow-rename off


# Copy mode styling
set -g mode-style "bg=#b4befe,fg=#1A1D23"

# Clock mode
set -g clock-mode-colour "#B4BEFE"
set -g clock-mode-style 24

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'rose-pine/tmux'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @resurrect-capture-pane-contents 'on'

set -g @yank_selection 'clipboard'
set -g @override_copy_command 'xclip -in -selection clipboard'

bind-key "m" run-shell "bash ~/dotfiles/tmux/scripts/sesh.sh"

set -g @plugin 'tmux-plugins/tpm'

run '~/.tmux/plugins/tpm/tpm'
